version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: 'chat_db'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1995
      MYSQL_DATABASE: chatdb

